### ISSUE TITLE
Add suport to ESXi 6.0 u2

### ISSUE THREAD

**Issue by trentasis** [op5/check_vmware_api#1]
hi,

Now we are using check_vmware_api 0.7.1 to monitor vcenter and esxi 5.1 u3
and is working great with perl SDK 5.1

Now I'm trying to use with a ESXi cluster with 6.0 u2 (vcenter and esxi
hosts) but with this versión we have problems with this versions.
Errors detected are unknow and timeout result after 60 seconds, and running 
from cli we detected that every check need more than 8 seconds, and with
5.1 is less tan 2 seconds. After this we have detected that if we add more tan 4
services then check begin to return unknow and timeout errors, and with
less that 4 services then works.

We have tried upgrading vsphere 6.0 u2 SDK but then is not working any
check (5.1 and 6.0). also tried to upgrade check vmware_api to latest
versions gorm git but error persist

It seems that ESXi 6.0 u2 is not supported with latest version...

How can I monitor correctly esxi and vcenter 5.1 and 6.0 with 
check_vmware_api?

**Comment by rhagman** [comment]
Hi!
The plugin currently supports check status of vmware esx 3.x, esxi server, vsphere 4 and vsphere 5.
Thanks for adding an issue to add support for later versions. This might get implemented in the future.

**Comment by trentasis** [comment]
solved changing hostname server by fqdn name
