### ISSUE TITLE
Login Event Spam

### ISSUE THREAD

**Issue by Klang0340** [op5/check_vmware_api#3]
Good morning all,

I had previously used this plugin however our VMWare Team received a login event for every single service check performed. As we have many ESX hosts and performed a lot of checks we ended up producing millions of login events to the point they felt the performance of the VCenter Host was being impacted by the monitoring. Has this plugin been developed to hold a steady connection versus building a new one for each check?

**Comment by mfalkvidd** [comment]
Hi! Unfortunately, no-one has developed such a solution so far.

**Comment by Klang0340** [comment]
Darn,

      Thanks for the feedback! Unfortunately I won't be able to monitor our ESX hosts with this plugin until the audit spam is cut down. Such a great plugin, just needs to hold a steady connection versus tearing down every check.
